name: lorry_wood_logger
description: Simple, offline-first Flutter app to record lorry wood deliveries.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"


flutter_native_splash:
  color: "#FFFFFF"                    # background color
  image: assets/images/bg1.jpg        # your splash image
  android_12:
    color: "#FFFFFF"
    image: assets/images/bg1.jpg
  ios: true
  web: false


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  uuid: ^4.4.0
  intl: ^0.19.0
  share_plus: ^10.0.2
  pdf: ^3.11.0
  path_provider: ^2.1.4
  open_filex: ^4.4.0
  file_saver: ^0.2.12
  printing: ^5.13.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg1.jpg